# Generated by Django 3.2.5 on 2021-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='ricette',
            field=models.ManyToManyField(to='app.Ricetta'),
        ),
    ]
