# Generated by Django 3.2.5 on 2021-09-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carta_ricette'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carta',
            new_name='MenuSettimana',
        ),
    ]
