# Generated by Django 3.2.5 on 2021-09-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_menusettimana_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusettimana',
            old_name='tags',
            new_name='tag',
        ),
    ]
