# Generated by Django 3.2.5 on 2021-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210904_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusettimana',
            name='ricette',
            field=models.ManyToManyField(blank=True, null=True, to='app.tagRicetta'),
        ),
    ]
