# Generated by Django 3.2.5 on 2021-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_tagricetta_ricetta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='ricette',
            field=models.ManyToManyField(blank=True, null=True, to='app.Ricetta'),
        ),
        migrations.DeleteModel(
            name='tagRicetta',
        ),
    ]
