# Generated by Django 3.2.5 on 2021-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210904_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusettimana',
            name='approvato',
            field=models.BooleanField(default=False),
        ),
    ]
