# Generated by Django 3.2.5 on 2021-09-22 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_menusettimana_approvato'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteImpianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listino', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.impianto')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingrediente')),
            ],
            options={
                'unique_together': {('ingrediente', 'impianto')},
            },
        ),
    ]
