# Generated by Django 3.2.5 on 2021-10-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_ingredienteimpianto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusettimana',
            name='approvato',
        ),
        migrations.AddField(
            model_name='menusettimana',
            name='approvatore',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menusettimana',
            name='creatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chef'),
        ),
    ]
