# Generated by Django 3.2.5 on 2021-10-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_menusettimana_creatore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chef'),
        ),
    ]
