# Generated by Django 3.2.5 on 2021-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_menusettimana_creatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('nome', 'nome')},
        ),
        migrations.AlterModelOptions(
            name='impianto',
            options={'ordering': ('area', 'nome')},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ('nome_generico', 'nome_generico')},
        ),
        migrations.AlterModelOptions(
            name='portata',
            options={'ordering': ('nome', 'nome')},
        ),
        migrations.AddField(
            model_name='menusettimana',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
