# Generated by Django 3.2.5 on 2021-10-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211006_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusettimana',
            old_name='approvato',
            new_name='approvazione',
        ),
    ]
