# Generated by Django 3.2.5 on 2021-10-06 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_menusettimana_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
