# Generated by Django 3.2.5 on 2021-10-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_chefmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefManager',
        ),
    ]
