# Generated by Django 3.2.5 on 2021-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_chefmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergene',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='allergeni/'),
        ),
    ]
