# Generated by Django 3.2.5 on 2021-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_allergene_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('nome', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
