# Generated by Django 3.2.5 on 2021-10-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_fornitore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornitore',
            options={'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='ingredienteimpianto',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fornitore'),
        ),
    ]
