# Generated by Django 3.2.5 on 2021-10-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211007_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusettimana',
            old_name='approvazione',
            new_name='aggiornato',
        ),
    ]
