# Generated by Django 3.2.5 on 2021-10-07 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_rename_approvazione_menusettimana_aggiornato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatore', to='auth.user'),
        ),
    ]
