# Generated by Django 3.2.5 on 2021-10-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20211009_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteimpianto',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fornitore'),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='portata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.portata'),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag'),
        ),
    ]
