# Generated by Django 3.2.5 on 2021-10-13 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_allergene_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
