# Generated by Django 3.2.5 on 2021-10-13 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_menusettimana_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='aggiornato',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
