# Generated by Django 3.2.5 on 2021-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_menusettimana_aggiornato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='aggiornato',
            field=models.DateTimeField(editable=False),
        ),
    ]
