# Generated by Django 3.2.5 on 2021-10-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_historymenu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menusettimana'),
        ),
    ]
