# Generated by Django 3.2.5 on 2021-10-13 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_historymenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 19, 23, 933164, tzinfo=utc), editable=False),
        ),
    ]
