# Generated by Django 3.2.5 on 2021-10-13 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_menusettimana_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymenu',
            name='istante',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 26, 23, 994795, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 26, 23, 993795, tzinfo=utc), editable=False),
        ),
    ]
