# Generated by Django 3.2.5 on 2021-10-13 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20211013_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymenu',
            name='istante',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 28, 28, 946923, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 28, 28, 945923, tzinfo=utc), editable=False),
        ),
    ]
