# Generated by Django 3.2.5 on 2021-10-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20211013_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymenu',
            name='istante',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='menusettimana',
            name='creazione',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
