# Generated by Django 3.2.5 on 2021-10-13 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0049_auto_20211013_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historymenu',
            unique_together={('menu', 'text', 'user')},
        ),
    ]
