# Generated by Django 3.2.5 on 2021-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_historymenu_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posizione',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
