# Generated by Django 3.2.5 on 2021-10-14 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_tag_posizione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('posizione',)},
        ),
        migrations.AlterField(
            model_name='tag',
            name='posizione',
            field=models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('posizione',)},
        ),
    ]
