# Generated by Django 3.2.5 on 2021-10-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_tag_posizione'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
    ]
