# Generated by Django 3.2.5 on 2021-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_menusettimana_giorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusettimana',
            name='giorno',
            field=models.CharField(choices=[('Lunedi', 'Lunedi'), ('Martedi', 'Martedi'), ('Mercoledi', 'Mercoledi'), ('Giovedi', 'Giovedi'), ('Venerdi', 'Venerdi')], max_length=9),
        ),
    ]
