# Generated by Django 3.2.8 on 2021-11-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_area_capo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.capoarea'),
        ),
    ]
