# Generated by Django 3.2.8 on 2021-11-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_area_capo'),
    ]

    operations = [
        migrations.AddField(
            model_name='impianto',
            name='classificazione',
            field=models.CharField(blank=True, choices=[('Classico', 'Classico'), ('Plus', 'Plus'), ('Premium', 'Premium')], max_length=8, null=True),
        ),
    ]
