# Generated by Django 3.2.8 on 2021-11-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_ricetta_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impianto',
            name='classificazione',
            field=models.CharField(choices=[('Classico', 'Classico'), ('Plus', 'Plus'), ('Premium', 'Premium')], max_length=8),
        ),
    ]
