# Generated by Django 3.2.8 on 2021-11-10 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_ricetta_special'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portata',
            options={'ordering': ('posizione',)},
        ),
        migrations.AddField(
            model_name='portata',
            name='posizione',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
